[tool.poetry]
name = "broadcast"
version = "0.1.0"
description = ""
authors = ["fdv1 <francois@pytek.io>"]
readme = "README.md"
packages = [{include = "broadcast"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
